//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Bretano.WebMiddle.FrontEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.WebUserCompany = new HashSet<WebUserCompany>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string connStringName { get; set; }
        public string dataBaseName { get; set; }
        public string sapUser { get; set; }
        public string sapPassword { get; set; }
        public string logo { get; set; }
    
        public virtual ICollection<WebUserCompany> WebUserCompany { get; set; }
    }
}
