//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Bretano.WebMiddle.FrontEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyParameter
    {
        public int idCompany { get; set; }
        public int idParameter { get; set; }
        public string value { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Parameter Parameter { get; set; }
    }
}
