//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Bretano.WebMiddle.FrontEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDR
    {
        public ORDR()
        {
            this.RDR1 = new HashSet<RDR1>();
        }
    
        public int id { get; set; }
        public Nullable<int> docEntry { get; set; }
        public string cardCode { get; set; }
        public int series { get; set; }
        public System.DateTime docDate { get; set; }
        public System.DateTime docDueDate { get; set; }
        public System.DateTime taxDate { get; set; }
        public string shipToCode { get; set; }
        public string payToCode { get; set; }
        public int groupNum { get; set; }
        public string comments { get; set; }
        public Nullable<int> slpCode { get; set; }
        public string uCssComentarios { get; set; }
        public string uOrkUsuarioWeb { get; set; }
        public string uLatitud { get; set; }
        public string uLongitud { get; set; }
        public Nullable<int> idCompania { get; set; }
    
        public virtual ICollection<RDR1> RDR1 { get; set; }
    }
}
