//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Bretano.WebMiddle.FrontEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessQueue
    {
        public int id { get; set; }
        public int idCompany { get; set; }
        public string actionType { get; set; }
        public int idTarget { get; set; }
        public System.DateTime addedToQueue { get; set; }
        public Nullable<System.DateTime> processed { get; set; }
        public string logMessage { get; set; }
        public Nullable<bool> sucess { get; set; }
    }
}
