//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Bretano.WebMiddle.FrontEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUT1
    {
        public int orderId { get; set; }
        public string itemCode { get; set; }
        public decimal quantity { get; set; }
        public string whsCode { get; set; }
        public decimal price { get; set; }
        public string taxCode { get; set; }
        public string ocrCode { get; set; }
        public string uCssEnvaseDevol { get; set; }
    
        public virtual OQUT OQUT { get; set; }
    }
}
