//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Bretano.WebMiddle.FrontEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebUserCompany
    {
        public int webUserId { get; set; }
        public int companyId { get; set; }
        public bool admin { get; set; }
        public bool customerCreator { get; set; }
        public bool purchaseOrderCreator { get; set; }
        public int slpCode { get; set; }
        public bool orderApprover { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual WebUser WebUser { get; set; }
    }
}
