//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Bretano.WebMiddle.FrontEnd.DAL
{
    using Orkidea.Bretano.WebMiddle.FrontEnd.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QcaWebMiddleEntities : DbContext
    {
        public QcaWebMiddleEntities()
            : base("name=QcaWebMiddleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WebUser> WebUser { get; set; }
        public virtual DbSet<OQUT> OQUT { get; set; }
        public virtual DbSet<QUT1> QUT1 { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyParameter> CompanyParameter { get; set; }
        public virtual DbSet<Parameter> Parameter { get; set; }
        public virtual DbSet<RDR1> RDR1 { get; set; }
        public virtual DbSet<ORDR> ORDR { get; set; }
        public virtual DbSet<WebUserCompany> WebUserCompany { get; set; }
    }
}
